### ISSUE TITLE
Safety when node clusters are used

### ISSUE THREAD

**Issue by khalilTN** [adamhalasz/uniqid#1]
Hi,

The uniqId is generated from Date.getTime() function, the uniquness is guaranteed when running only one node process, but what about running a node app on multiple clusters, probably, a collision may occure.

Thanks

**Comment by adamhalasz** [comment]
Hi @khalilTN 

You are right. However the purpose of this module is speed and simplicity for single process applications. If you need to make sure the ID's are unique on clusters you can do 2 things;

1) Just use [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) with something like the [uuid](https://www.npmjs.com/package/uuid) module. You might still run into generating 2 identical ID's but the chances are astronomical.

2) Centralize. Generate your Unique ID's on a single machine (MACHINE A). Every other machine (MACHINE X, Y, Z) requests unique id's from MACHINE A. Since MACHINE A is running on a single process the uniqueness of the ID's are guaranteed again. The cost is speed and network overhead, but hey clustering is not easy :)

Let me know if you have any other suggestions or questions.

Kind Regards,
Adam

**Comment by adamhalasz** [comment]
Well... I just created v2 which uses the Process ID and the OS's Name. The PID will be always unique to every process within a Single Machine. That solves the multiple process issue. 

Now for making sure the ID's are unique even in multi cluster / multi machine environments I use the first 3 letters of the Machine's Name. With v2 You can safely generate unique id's even with many concurrent machines if the name of the machines differ.

Hope this solves your issue :)

**Comment by khalilTN** [comment]
Hi,
I'm glad i contributed to the evolution of this Simple/Perfect Module.
Those who seek to use mutli-machine should guarantee that machine names differ.
What about using mac addresses (of one of the interfaces, if multiple interfaces), i think the problem will be solved permanently.
Thanks !

**Comment by adamhalasz** [comment]
@khalilTN thanks a lot! As I was mentioning to @Offirmo, you're right the Mac address would solve the uniqueness of the id's permanently however, I also want to make sure the length of the ID's remain as small as possible. I will think more about this over the weekend. :) 

Since v2 solves your problem, I will close this issue but let me know if you have any other questions/ideas.

Thanks,
Adam

**Comment by adamhalasz** [comment]
@khalilTN v3 now uses mac addresses :)

**Comment by khalilTN** [comment]
Thanks a lot !
