### ISSUE TITLE
v5.1.0 throwing error on IE11

### ISSUE THREAD

**Issue by eragon512** [adamhalasz/uniqid#32]
Bundling `uniqid@5.1.0` in a browser-side application causes the application to fail loading on IE11.

**Comment by afsal008** [comment]
Hi @adamhalasz When building app in ubuntu, uniqid plugins exports are with default parameters
```
//  Exports
// ================================================
module.exports = module.exports.default = function(prefix = '', suffix = ''){ return prefix + address + pid + now().toString(36) + suffix; }
module.exports.process = function(prefix = '', suffix = ''){ return prefix + pid + now().toString(36) + suffix; }
module.exports.time    = function(prefix = '', suffix = ''){ return prefix + now().toString(36) + suffix; }
```

When building in Windows no such issue.
Could you please get me some help?

**Comment by ValentinCreative** [comment]
Same issue here building with mac os, had to downgrade uniqid.

**Comment by HernanGH** [comment]
Same issue with uniqid@5.1.0

**Comment by diogofscmariano** [comment]
This happening because the module is not offering a transpiled version, and this was caused by: https://github.com/adamhalasz/uniqid/pull/21. On my side I added the webpack configuration to transpile this module, through `exclude: /node_modules\/(?!(uniqid)\/).*/,`. This is the rule we generally use, avoiding the transpilation of everything inside node_modules

**Comment by Inveth** [comment]
Happens to me too - should we roll back to some previous version?

**Comment by HernanGH** [comment]
Yes, I roll back at version 4.4.1

**Comment by Inveth** [comment]
Thanks @adamhalasz for updating -> bundles just fine now.

**Comment by adamhalasz** [comment]
Glad to hear it’s working now! :) Thanks for the fix @nick-smit
