### ISSUE TITLE
browserify - stopped working in browser

### ISSUE THREAD

**Issue by lfamorim** [adamhalasz/uniqid#4]

**Comment by adamhalasz** [comment]
Hey @lfamorim,

Sorry to hear that. Can you give me the version number of uniqid and browserify. Also what browser do you use and can you send an error trace?

Thanks,
Adam

**Comment by ben-eb** [comment]
I think this might be related; I'm getting failures when building with webpack;

https://travis-ci.org/ben-eb/cssnano/jobs/144187953#L2002

I upgraded to 3.0.0 in postcss-filter-plugins@2.0.1, where this error started to occur. Downgrading the dependency to either version 1 or version 2 does not exhibit this error.

Related: https://github.com/ben-eb/cssnano/pull/226

**Comment by adamhalasz** [comment]
@ben-eb Thank you for letting me know. I'm really sorry that it's causing issues! I'm looking into this right now. The problem is most likely coming from the `macaddress` dependency that I added recently and maybe the way I wait for the address.

I will test it in webpack and browserify and fix it asap. In the meantime using the older versions as you mentioned or using v3 with these methods might be a quick temporary solution:

```js
uniqid.process()
uniqid.time()
```

Kind Regards,
Adam

**Comment by ben-eb** [comment]
Thanks Adam. For now I'll pin postcss-filter-plugins to version 2 until this is resolved.

**Comment by adamhalasz** [comment]
hey @ben-eb @lfamorim 

**I just uploaded v4.0** ([#64de90f](https://github.com/adamhalasz/uniqid/commit/64de90f67c392b5af0f8c38652a24059705a564d)) to Github which has 2 new examples:
- [Webpack Example](https://github.com/adamhalasz/uniqid/tree/master/examples/webpack)
- [Browserify Example](https://github.com/adamhalasz/uniqid/tree/master/examples/browserify)

**The problem was caused by 2 issues**
- the `process` object and the `process.pid` is not defined in browsers
- the `macaddress` module fails to load inside browsers. 

**The solution**
Just fall back to the original uniqid() v1 function which is good enough for the browsers since it's the single process, single machine case anyway.

Can you guys test it to see if it works for you before I publish it to NPM as well?

Thanks,
Adam

**Comment by ben-eb** [comment]
Works for me, thanks for the quick turnaround! 👍

**Comment by adamhalasz** [comment]
@ben-eb glad to hear that! My pleasure!
